### ISSUE TITLE
Attribute should not freeze its primitive type

### ISSUE THREAD

**Issue by solnic** [dkubb/axiom#46]
This is too aggressive, axiom should not freeze globally available class objects. This can break people's code and currently it breaks all specs in rom-session because rspec tries to monkey-patch `BasicObject` which happens to be frozen.

**Comment by mbj** [comment]
@dkubb. Lets default `ice_nine` to skip instances of `Class`. I think it creates more problems. Only our community does like this kind of freezing, and I think we can freeze our, sometimes dynamically, created classes by ourselves.

If we still recurse into ivars of `Class` should be discussed.

**Comment by solnic** [comment]
Yes I think we should be extra careful when using Adamantium with deep freezing. This can and probably will piss off many people if our libs freeze things they don't own.

**Comment by mbj** [comment]
We could also provide a mixin `Adamantium::ClassFreeze` that "whitelist our classes" to be frozen. Or whitelist the namespaces we "own".

**Comment by solnic** [comment]
I don't think it makes sense. Open classes is one of the ruby _features_. We could not agree with it but it doesn't matter. A ton of ruby libs change classes through monkey-patching whether we like it or not and we should be good citizens here and skip freezing classes just because of that.

It's totally fine to freeze stuff we generate, as you said. So once we start generating mappers on the fly we could freeze them.

**Comment by mbj** [comment]
@solnic I'm okay with freezing some of my classes. But I dont think I'll invest time into this soon.

**Comment by snusnu** [comment]
@solnic @mbj @dkubb imo our support code **MUST** allow us to _not freeze_ anything we do not own. It's ok that we (deep) freeze stuff when we own the complete object graph, but that freezing should _never_ step outside our own boundaries without us having a chance to stop it from doing so. It's simply not friendly to alter code we do not own, and it can be the source of subtle, annoying bugs.

**Comment by snusnu** [comment]
There's also a case where `equalizer` deep freezes stuff in the object graph, and there's no way of stopping that. I see no reason why equality behavior must be tied to deep frozen instances only.

For reference, [this code](https://github.com/snusnu/substation/tree/adamantium-problem) demonstrates that problem with `equalizer`.

**Comment by snusnu** [comment]
In fact, I think we're doing exactly what we don't want others to do. Modifying ruby's behavior globally. We typically don't like core extensions too much, because they change the behavior of already existing classes. If we start to (deep) freeze people's code, we're essentially doing the same. Modify it. If only for the sake of not being able to modify it anymore.

**Comment by solnic** [comment]
@snusnu current "version" of [equalizer used in axiom](https://github.com/dkubb/axiom/blob/master/lib/axiom/support/equalizer.rb) automatically includes Adamantium when you include an equalizer module

We should update axiom to use the extracted version of equalizer and include adamantium separately using "flat" module where appropriate

**Comment by snusnu** [comment]
@solnic agreed

**Comment by solnic** [comment]
@dkubb bump...

**Comment by dkubb** [comment]
This should no longer be an issue because Attribute no longer holds a reference to a primitive, but rather an `Axiom::Types::Type` instance.
